sonar.projectKey=petclinic
sonar.projectName=petclinic
sonar.sources=petclinc/src/main/java
sonar.tests=petclinc/src/test/java
sonar.java.binaries=petclinc/target/classes
sonar.java.test.binaries=petclinc/target/test-classes
sonar.junit.reportPaths=petclinc/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=petclinc/target/site/jacoco/jacoco.xml
sonar.exclusions=**/target/**,**/node_modules/**,**/.git/**,**/generated/**